import "./globals.css";
import NavBar from "./components/Navbr";
import Footer from './components/Footer';

export const metadata = {
  title: "Filipina Dream Girl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <NavBar />
        <main className="p-0 w-full lg:w-[100%]">
          {children}
        </main>
        <Footer companyName="Filipina Dream Girl" year={new Date().getFullYear()} />
      </body>
    </html>
  );
}
